spring:
  freemarker:
    suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/bookmanager?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

server:
  port: 8080

mybatis:
  config-location: classpath:mybatis-config.xml
